var animalList = [
  {
    Name: "Wishbone",
    Type: "Dog",
    Breed: "Australian Shephard Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 1,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 20579,
      MicroChipNo: 985113004709947,
    },
    Suitability: "",
    AbtMe:
      "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
    ],
  },
  {
    Name: "Pepper",
    Type: "Dog",
    Breed: "American Pit Bull Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "White",
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 2,
      Weeks: 4,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23328,
      MicroChipNo: 985113005872880,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
    ],
  },
  {
    Name: "Fernando",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23907,
      MicroChipNo: 985113006286714,
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
    ],
  },
  {
    Name: "Hemingway",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 3,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23897,
      MicroChipNo: "",
    },
    Suitability: "<br>Doesn't Like Cats<br>Special Needs",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
    ],
  },

  {
    Name: "Freya",
    Type: "Dog",
    Breed: "Blue Heeler Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "Blue",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 1,
      Months: 7,
      Weeks: 0,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23867,
      MicroChipNo: "985113006286705",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71366.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/db9e981c-16ca-4b6c-a4c1-3be8d45786e3.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/a41cb915-e0be-44fa-b13d-bfc1d6c69311.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/020a57b7-dc4b-419f-8760-122e224d4456.jpeg",
    ],
  },
  {
    Name: "Bailey",
    Type: "Dog",
    Breed: "Collie Smooth Cross",
    SecondBreed: "Golden Retriever",
    Sex: "Female",
    Color: "Gold",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 11,
      Months: 0,
      Weeks: 0,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24150,
      MicroChipNo: "985121006365498",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71543.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/e74bbf5a-5a20-48c3-9b08-44608838584b.jpeg",
    ],
  },
  {
    Name: "Tonk",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 7,
      Weeks: 0,
      approx: false,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 22484,
      MicroChipNo: "981020033392362",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/71471_th_600.jpg",
    ],
  },
  {
    Name: "Ivan",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey Tabby",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 0,
      Weeks: 1,
      approx: false,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24029,
      MicroChipNo: "985113006287119",
    },
    Suitability: "Doesn't Like Cats\nSpecial Needs\nLaid back\nSocial",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71454.jpg",
    ],
  },

  {
    Name: "Snickerdoodle",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "Grey Tabby",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 6,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 18366,
      MicroChipNo: "985113003498608",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/68308_th_600.jpg",
    ],
  },

  {
    Name: "Ichabod",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Grey",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 6,
      Weeks: 2,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24052,
      MicroChipNo: "985113006286493",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71476.jpg",
    ],
  },
  {
    Name: "Juniper",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "Brown Tabby",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 3,
      Months: 0,
      Weeks: 0,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24127,
      MicroChipNo: "985113006287191",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71523.jpeg",
    ],
  },
  {
    Name: "Juliana",
    Type: "Cat",
    Breed: "Domestic Short Hair Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "Nuted Tortoiseshell",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 3,
      Months: 0,
      Weeks: 0,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24105,
      MicroChipNo: "",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71532.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/cab0b5ad-9867-4cb6-a9ad-a5b79a5dd1ce.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c879315b-07e3-41fd-ad1d-0c4d84cdb901.jpeg",
    ],
  },

  {
    Name: "Moose",
    Type: "Dog",
    Breed: "Hound Cross",
    SecondBreed: "Shepherd",
    Sex: "Male",
    Color: "Tan",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 4,
      Weeks: 1,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24105,
      MicroChipNo: "",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/70955_th_600.jpeg",
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/0ee5039e-f038-4ec4-adbe-a8ec908456ad_th_600.jpg",
    ],
  },
  {
    Name: "Ashley",
    Type: "Dog",
    Breed: "Hound Cross",
    SecondBreed: "Pit Bull",
    Sex: "Female",
    Color: "Brindle",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 2,
      Months: 4,
      Weeks: 1,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24018,
      MicroChipNo: "985113006299432",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/71448_th_600.jpg",
    ],
  },
  {
    Name: "Samantha",
    Type: "Dog",
    Breed: "Hound Cross",
    SecondBreed: "",
    Sex: "Female",
    Color: "Black/Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 1,
      Months: 0,
      Weeks: 4,
      approx: false,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 24141,
      MicroChipNo: "982091066623238",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71540.jpg",
    ],
  },
  {
    Name: "Gideon",
    Type: "Dog",
    Breed: "Labrador Cross",
    SecondBreed: "",
    Sex: "Male",
    Color: "Black",
    Declawed: false,
    SpayedNeutered: true,
    Age: {
      Years: 1,
      Months: 6,
      Weeks: 0,
      approx: true,
    },
    Details: {
      Health: true,
      Vacc: true,
      Worming: true,
      Microchpped: true,
    },
    AnimalId: {
      ID: 23900,
      MicroChipNo: "985113006300266",
    },
    Suitability: "",
    AbtMe: "",
    Pics: [
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71389.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/0d9dc03e-defe-4d01-b30c-1b52a36874ae_th_600.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos/lostfound/e9a16932-d4f1-4596-a882-bb2989052723_th_600.jpg",
      "http://kentoncountypets.shelterbuddy.com/photos//lostfound/98e34cd9-d61b-4507-a9d3-85e73f7ae30b.jpeg",
    ],
  },
  //   {
  //     Name: "Wishbone",
  //     Type: "Dog",
  //     Breed: "Australian Shephard Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Black",
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 1,
  //       Weeks: 2,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 20579,
  //       MicroChipNo: 985113004709947,
  //     },
  //     Suitability: "",
  //     AbtMe:
  //       "Wishbone is a super sweet playful guy! He is around a 2 years old, but is still very much a puppy. He loves people and he, like any youngster, will need basic manner training and a patient home willing to put their time and energy into him. Wishbone also seems to play well with other dogs! His perfect doggy pal would be one that can keep up yet be tolerant of his playful antics. He would benefit from a home willing to exhaust his energy and keep him active . Wishbone might jump on you or play mouth because he is young and still learning. Wishbone will require a home with children 13 years and older because he gets so playful and excited he doesn't realize his size and strength. He truly is a smart young man just needs the right home to spoil him rotten! My past owner went through the process of getting me registered as an Emotional Support Animal as well! And I have the Certificate to prove it!",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/69695.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2d2c50cb-6751-4532-a398-877422a56c44.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/ae164deb-1077-426f-bace-f38307138814.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c95a20b7-54d9-43a4-a541-159f9eb39a51.jpeg",
  //     ],
  //   },
  //   {
  //     Name: "Pepper",
  //     Type: "Dog",
  //     Breed: "American Pit Bull Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "White",
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 2,
  //       Weeks: 4,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 23328,
  //       MicroChipNo: 985113005872880,
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com//photos/lostfound/71168_th_600.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/5ff135bb-000e-4220-8aa0-790af95892c0.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/334112a8-a782-403c-8ea0-36e490a1a486.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/2004c2ad-2bf6-4661-90c5-1bcd3378529f.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Fernando",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Black",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 0,
  //       Weeks: 3,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 23907,
  //       MicroChipNo: 985113006286714,
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71393.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Hemingway",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Grey",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 0,
  //       Weeks: 3,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 23897,
  //       MicroChipNo: "",
  //     },
  //     Suitability: "<br>Doesn't Like Cats<br>Special Needs",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71387.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/42c9c930-fb07-445b-a08e-cd83c438c515.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/9d5a88d5-bfd5-4d78-b7cd-8e91bdda0bdd.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/34d4696f-2735-4a6e-b266-210357ff5d74.jpeg",
  //     ],
  //   },

  //   {
  //     Name: "Freya",
  //     Type: "Dog",
  //     Breed: "Blue Heeler Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "Blue",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 1,
  //       Months: 7,
  //       Weeks: 0,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 23867,
  //       MicroChipNo: "985113006286705",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71366.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/db9e981c-16ca-4b6c-a4c1-3be8d45786e3.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/a41cb915-e0be-44fa-b13d-bfc1d6c69311.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/020a57b7-dc4b-419f-8760-122e224d4456.jpeg",
  //     ],
  //   },
  //   {
  //     Name: "Bailey",
  //     Type: "Dog",
  //     Breed: "Collie Smooth Cross",
  //     SecondBreed: "Golden Retriever",
  //     Sex: "Female",
  //     Color: "Gold",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 11,
  //       Months: 0,
  //       Weeks: 0,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24150,
  //       MicroChipNo: "985121006365498",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71543.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/e74bbf5a-5a20-48c3-9b08-44608838584b.jpeg",
  //     ],
  //   },
  //   {
  //     Name: "Tonk",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Black",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 7,
  //       Weeks: 0,
  //       approx: false,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 22484,
  //       MicroChipNo: "981020033392362",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/71471_th_600.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Ivan",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Grey Tabby",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 0,
  //       Weeks: 1,
  //       approx: false,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24029,
  //       MicroChipNo: "985113006287119",
  //     },
  //     Suitability: "Doesn't Like Cats\nSpecial Needs\nLaid back\nSocial",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71454.jpg",
  //     ],
  //   },

  //   {
  //     Name: "Snickerdoodle",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "Grey Tabby",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 6,
  //       Weeks: 2,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 18366,
  //       MicroChipNo: "985113003498608",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/68308_th_600.jpg",
  //     ],
  //   },

  //   {
  //     Name: "Ichabod",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Grey",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 6,
  //       Weeks: 2,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24052,
  //       MicroChipNo: "985113006286493",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71476.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Juniper",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "Brown Tabby",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 3,
  //       Months: 0,
  //       Weeks: 0,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24127,
  //       MicroChipNo: "985113006287191",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71523.jpeg",
  //     ],
  //   },
  //   {
  //     Name: "Juliana",
  //     Type: "Cat",
  //     Breed: "Domestic Short Hair Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "Nuted Tortoiseshell",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 3,
  //       Months: 0,
  //       Weeks: 0,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24105,
  //       MicroChipNo: "",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71532.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/cab0b5ad-9867-4cb6-a9ad-a5b79a5dd1ce.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/c879315b-07e3-41fd-ad1d-0c4d84cdb901.jpeg",
  //     ],
  //   },

  //   {
  //     Name: "Moose",
  //     Type: "Dog",
  //     Breed: "Hound Cross",
  //     SecondBreed: "Shepherd",
  //     Sex: "Male",
  //     Color: "Tan",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 4,
  //       Weeks: 1,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24105,
  //       MicroChipNo: "",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/70955_th_600.jpeg",
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/0ee5039e-f038-4ec4-adbe-a8ec908456ad_th_600.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Ashley",
  //     Type: "Dog",
  //     Breed: "Hound Cross",
  //     SecondBreed: "Pit Bull",
  //     Sex: "Female",
  //     Color: "Brindle",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 2,
  //       Months: 4,
  //       Weeks: 1,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24018,
  //       MicroChipNo: "985113006299432",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/71448_th_600.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Samantha",
  //     Type: "Dog",
  //     Breed: "Hound Cross",
  //     SecondBreed: "",
  //     Sex: "Female",
  //     Color: "Black/Black",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 1,
  //       Months: 0,
  //       Weeks: 4,
  //       approx: false,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 24141,
  //       MicroChipNo: "982091066623238",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71540.jpg",
  //     ],
  //   },
  //   {
  //     Name: "Gideon",
  //     Type: "Dog",
  //     Breed: "Labrador Cross",
  //     SecondBreed: "",
  //     Sex: "Male",
  //     Color: "Black",
  //     Declawed: false,
  //     SpayedNeutered: true,
  //     Age: {
  //       Years: 1,
  //       Months: 6,
  //       Weeks: 0,
  //       approx: true,
  //     },
  //     Details: {
  //       Health: true,
  //       Vacc: true,
  //       Worming: true,
  //       Microchpped: true,
  //     },
  //     AnimalId: {
  //       ID: 23900,
  //       MicroChipNo: "985113006300266",
  //     },
  //     Suitability: "",
  //     AbtMe: "",
  //     Pics: [
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/71389.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/0d9dc03e-defe-4d01-b30c-1b52a36874ae_th_600.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos/lostfound/e9a16932-d4f1-4596-a882-bb2989052723_th_600.jpg",
  //       "http://kentoncountypets.shelterbuddy.com/photos//lostfound/98e34cd9-d61b-4507-a9d3-85e73f7ae30b.jpeg",
  //     ],
  //   },
];
